

stages:          # List of stages for jobs, and their order of execution
  - build
  - deploy

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  tags: [shell]
  script:
    - echo "Compiling the code..."
    - echo "Compile complete."
    - mkdir -p .cache .local
#    - docker run -u $(id -u):$(id -g) --rm -v ${pwd}/.local/:/.local/ -v ${pwd}/.cache/:/.cache/ -v $(pwd)/:/src -w /src dxkjyjy.cn/lib/python sh -c "proxychains pip install -r requirements.txt && pyinstaller -c alg_pod.py"
    - docker run --rm -v ${pwd}/.local/:/.local/ -v ${pwd}/.cache/:/.cache/ -v $(pwd)/:/src -w /src dxkjyjy.cn/lib/python sh -c "proxychains pip install -r requirements.txt && pyinstaller -c alg_pod.py && chown -R $(id -u):$(id -g) dist"
    - tar czpvf algbin.tar.gz -C dist/alg_pod .
  artifacts:
    paths:
      - algbin.tar.gz


deploy-job:      # This job runs in the deploy stage.
  tags: [golang,docker]
  stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
    - ver=$(date +'%Y%m%d.%H%M%S')
    - mc cp ./algbin.tar.gz ydn/gitlab-runner/iss-alg/algbin-${ver}.tar.gz
