name: ISS Alg Pod with Python3.8 + Opencv Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v4
      with:
        images: f7star/iss-alg-pod
        tags: |
          type=raw,value=latest

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build and Push Golang
      uses: docker/build-push-action@v4
      with:
        buildkit: true  # Enable Docker BuildKit
        push: true
        file: Dockerfile  # 确保你的项目中有 Dockerfile
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
      
